2021/07/23 12:56:37 [error] [exception.Error] Error: Call to undefined function imagettfbbox() in /var/www/html/web/widgets/captcha/CCaptchaAction.php:208
Stack trace:
#0 /var/www/html/web/widgets/captcha/CCaptchaAction.php(111): CCaptchaAction->renderImage('rmzownh')
#1 /var/www/html/web/CController.php(300): CCaptchaAction->run()
#2 /var/www/html/web/CController.php(278): CController->runAction(Object(CCaptchaAction))
#3 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#4 /var/www/html/web/CWebApplication.php(332): CController->run('captcha')
#5 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('site/captcha')
#6 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#7 /var/www/html/testapp/index.php(11): CApplication->run()
#8 {main} REQUEST_URI=/testapp/index.php?r=site/captcha
2021/07/23 13:20:31 [error] [exception.Error] Error: Call to undefined function imagettfbbox() in /var/www/html/web/widgets/captcha/CCaptchaAction.php:208
Stack trace:
#0 /var/www/html/web/widgets/captcha/CCaptchaAction.php(111): CCaptchaAction->renderImage('rmzownh')
#1 /var/www/html/web/CController.php(300): CCaptchaAction->run()
#2 /var/www/html/web/CController.php(278): CController->runAction(Object(CCaptchaAction))
#3 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#4 /var/www/html/web/CWebApplication.php(332): CController->run('captcha')
#5 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('site/captcha')
#6 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#7 /var/www/html/testapp/index.php(11): CApplication->run()
#8 {main} REQUEST_URI=/testapp/index.php?r=site/captcha
2021/07/23 13:20:32 [error] [exception.Error] Error: Call to undefined function imagettfbbox() in /var/www/html/web/widgets/captcha/CCaptchaAction.php:208
Stack trace:
#0 /var/www/html/web/widgets/captcha/CCaptchaAction.php(111): CCaptchaAction->renderImage('rmzownh')
#1 /var/www/html/web/CController.php(300): CCaptchaAction->run()
#2 /var/www/html/web/CController.php(278): CController->runAction(Object(CCaptchaAction))
#3 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#4 /var/www/html/web/CWebApplication.php(332): CController->run('captcha')
#5 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('site/captcha')
#6 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#7 /var/www/html/testapp/index.php(11): CApplication->run()
#8 {main} REQUEST_URI=/testapp/index.php?r=site/captcha
2021/07/25 11:21:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in /var/www/html/web/CController.php:439
Stack trace:
#0 /var/www/html/web/CController.php(262): CController->missingAction('captcha')
#1 /var/www/html/web/CWebApplication.php(332): CController->run('captcha')
#2 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user/captcha')
#3 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#4 /var/www/html/testapp/index.php(11): CApplication->run()
#5 {main} REQUEST_URI=/testapp/index.php?r=user/captcha
2021/07/25 11:22:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "UserController/captcha".' in /var/www/html/web/CWebApplication.php:336
Stack trace:
#0 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('UserController/...')
#1 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#2 /var/www/html/testapp/index.php(11): CApplication->run()
#3 {main} REQUEST_URI=/testapp/index.php?r=UserController/captcha
2021/07/26 07:46:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No such file or directory' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:46:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection timed out' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:47:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection timed out' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:48:01 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:48:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:48:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:32 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:37 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:50:56 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:55:56 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 08:00:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/29 10:22:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/user
2021/07/29 10:30:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in /var/www/html/testapp/protected/controllers/UserController.php:165
Stack trace:
#0 /var/www/html/testapp/protected/controllers/UserController.php(58): UserController->loadUser()
#1 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionShow()
#2 /var/www/html/web/CController.php(300): CInlineAction->run()
#3 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#4 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#5 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#6 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#7 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#8 /var/www/html/web/CController.php(283): CFilterChain->run()
#9 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/html/web/CWebApplication.php(332): CController->run('show')
#11 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user/show')
#12 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#13 /var/www/html/testapp/index.php(11): CApplication->run()
#14 {main} REQUEST_URI=/testapp/user/show
2021/07/29 10:30:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in /var/www/html/testapp/protected/controllers/UserController.php:165
Stack trace:
#0 /var/www/html/testapp/protected/controllers/UserController.php(58): UserController->loadUser()
#1 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionShow()
#2 /var/www/html/web/CController.php(300): CInlineAction->run()
#3 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#4 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#5 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#6 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#7 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#8 /var/www/html/web/CController.php(283): CFilterChain->run()
#9 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/html/web/CWebApplication.php(332): CController->run('show')
#11 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user/show')
#12 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#13 /var/www/html/testapp/index.php(11): CApplication->run()
#14 {main} REQUEST_URI=/testapp/user/show/
2021/07/29 10:33:24 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/user
2021/07/29 10:34:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/user
2021/07/29 10:34:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/user
2021/07/29 11:13:20 [error] [exception.CException] exception 'CException' with message 'Property "User.title" is not defined.' in /var/www/html/base/CComponent.php:120
Stack trace:
#0 /var/www/html/db/ar/CActiveRecord.php(431): CComponent->__get('title')
#1 /var/www/html/testapp/protected/components/UserIdentity.php(46): CActiveRecord->__get('title')
#2 /var/www/html/testapp/protected/models/LoginForm.php(48): UserIdentity->authenticate()
#3 /var/www/html/validators/CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#4 /var/www/html/validators/CValidator.php(161): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /var/www/html/base/CModel.php(187): CValidator->validate(Object(LoginForm), NULL)
#6 /var/www/html/testapp/protected/controllers/SiteController.php(62): CModel->validate()
#7 /var/www/html/web/actions/CInlineAction.php(32): SiteController->actionLogin()
#8 /var/www/html/web/CController.php(300): CInlineAction->run()
#9 /var/www/html/web/CController.php(278): CController->runAction(Object(CInlineAction))
#10 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/html/web/CWebApplication.php(332): CController->run('login')
#12 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('site/login')
#13 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#14 /var/www/html/testapp/index.php(11): CApplication->run()
#15 {main} REQUEST_URI=/testapp/site/login
2021/07/29 11:15:22 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(CWebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('admin')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user/admin')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/user/admin
2021/07/29 11:26:55 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(CWebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('admin')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user/admin')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/user/admin
2021/07/29 11:27:08 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(CWebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('admin')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('product/admin')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/product/admin
2021/07/29 11:27:16 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(CWebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('admin')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('product/admin')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/product/admin
2021/07/29 11:51:06 [error] [php] Attempt to assign property of non-object (/var/www/html/testapp/protected/controllers/UserController.php:74)
Stack trace:
#0 /var/www/html/web/filters/CFilterChain.php(129): UserController->runAction()
#1 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#2 /var/www/html/web/CController.php(952): CAccessControlFilter->filter()
#3 /var/www/html/web/filters/CInlineFilter.php(59): UserController->filterAccessControl()
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter()
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): UserController->runActionWithFilters()
#7 /var/www/html/web/CWebApplication.php(332): UserController->run()
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController()
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CWebApplication->run()
REQUEST_URI=/testapp/user/create
2021/07/29 11:51:49 [error] [php] Attempt to assign property of non-object (/var/www/html/testapp/protected/controllers/UserController.php:74)
Stack trace:
#0 /var/www/html/web/filters/CFilterChain.php(129): UserController->runAction()
#1 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#2 /var/www/html/web/CController.php(952): CAccessControlFilter->filter()
#3 /var/www/html/web/filters/CInlineFilter.php(59): UserController->filterAccessControl()
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter()
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): UserController->runActionWithFilters()
#7 /var/www/html/web/CWebApplication.php(332): UserController->run()
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController()
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CWebApplication->run()
REQUEST_URI=/testapp/user/create
2021/07/29 11:52:29 [error] [php] Attempt to modify property of non-object (/var/www/html/testapp/protected/controllers/UserController.php:74)
Stack trace:
#0 /var/www/html/web/filters/CFilterChain.php(129): UserController->runAction()
#1 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#2 /var/www/html/web/CController.php(952): CAccessControlFilter->filter()
#3 /var/www/html/web/filters/CInlineFilter.php(59): UserController->filterAccessControl()
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter()
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): UserController->runActionWithFilters()
#7 /var/www/html/web/CWebApplication.php(332): UserController->run()
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController()
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CWebApplication->run()
REQUEST_URI=/testapp/user/create
2021/07/29 11:53:37 [error] [php] Attempt to modify property of non-object (/var/www/html/testapp/protected/controllers/UserController.php:75)
Stack trace:
#0 /var/www/html/web/filters/CFilterChain.php(129): UserController->runAction()
#1 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#2 /var/www/html/web/CController.php(952): CAccessControlFilter->filter()
#3 /var/www/html/web/filters/CInlineFilter.php(59): UserController->filterAccessControl()
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter()
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): UserController->runActionWithFilters()
#7 /var/www/html/web/CWebApplication.php(332): UserController->run()
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController()
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CWebApplication->run()
REQUEST_URI=/testapp/user/create
2021/08/02 07:38:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(120): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/user
2021/08/04 09:27:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(WebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/user
2021/08/04 09:27:58 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(WebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/user
2021/08/04 09:28:07 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(WebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/user
2021/08/04 10:37:41 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(WebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('admin')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('product/admin')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/product/admin
2021/08/04 10:55:15 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(WebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/user
2021/08/04 10:55:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(WebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/user
2021/08/04 11:04:07 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(WebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/user
2021/08/04 11:10:26 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(WebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('delete')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('product/delete/...')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/product/delete/id/6
2021/08/04 11:10:44 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(WebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('delete')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('product/delete/...')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/product/delete/id/5
2021/08/04 11:10:59 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(WebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('admin')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('product/admin')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/product/admin
2021/08/04 11:11:02 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(WebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('admin')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('product/admin')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/product/admin
2021/08/04 11:11:27 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(WebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('admin')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('product/admin')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/product/admin
2021/08/04 11:11:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/html/web/auth/CAccessControlFilter.php:123
Stack trace:
#0 /var/www/html/web/auth/CAccessControlFilter.php(104): CAccessControlFilter->accessDenied(Object(WebUser))
#1 /var/www/html/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#3 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/html/web/CController.php(283): CFilterChain->run()
#6 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/html/web/CWebApplication.php(332): CController->run('delete')
#8 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('product/delete/...')
#9 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#10 /var/www/html/testapp/index.php(11): CApplication->run()
#11 {main} REQUEST_URI=/testapp/product/delete/id/5
2021/08/04 11:48:28 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication." is not defined.' in /var/www/html/base/CComponent.php:120
Stack trace:
#0 /var/www/html/base/CModule.php(93): CComponent->__get('')
#1 /var/www/html/testapp/protected/views/layouts/main.php(40): CModule->__get('')
#2 /var/www/html/web/CBaseController.php(119): require('/var/www/html/t...')
#3 /var/www/html/web/CBaseController.php(88): CBaseController->renderInternal('/var/www/html/t...', Array, true)
#4 /var/www/html/web/CController.php(642): CBaseController->renderFile('/var/www/html/t...', Array, true)
#5 /var/www/html/testapp/protected/controllers/SiteController.php(28): CController->render('index')
#6 /var/www/html/web/actions/CInlineAction.php(32): SiteController->actionIndex()
#7 /var/www/html/web/CController.php(300): CInlineAction->run()
#8 /var/www/html/web/CController.php(278): CController->runAction(Object(CInlineAction))
#9 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/html/web/CWebApplication.php(332): CController->run('')
#11 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('')
#12 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#13 /var/www/html/testapp/index.php(11): CApplication->run()
#14 {main} REQUEST_URI=/testapp/index.php
2021/08/04 11:49:13 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.role" is not defined.' in /var/www/html/base/CComponent.php:120
Stack trace:
#0 /var/www/html/web/auth/CWebUser.php(97): CComponent->__get('role')
#1 /var/www/html/testapp/protected/views/layouts/main.php(40): CWebUser->__get('role')
#2 /var/www/html/web/CBaseController.php(119): require('/var/www/html/t...')
#3 /var/www/html/web/CBaseController.php(88): CBaseController->renderInternal('/var/www/html/t...', Array, true)
#4 /var/www/html/web/CController.php(642): CBaseController->renderFile('/var/www/html/t...', Array, true)
#5 /var/www/html/testapp/protected/controllers/SiteController.php(28): CController->render('index')
#6 /var/www/html/web/actions/CInlineAction.php(32): SiteController->actionIndex()
#7 /var/www/html/web/CController.php(300): CInlineAction->run()
#8 /var/www/html/web/CController.php(278): CController->runAction(Object(CInlineAction))
#9 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/html/web/CWebApplication.php(332): CController->run('')
#11 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('')
#12 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#13 /var/www/html/testapp/index.php(11): CApplication->run()
#14 {main} REQUEST_URI=/testapp/
2021/08/04 11:49:16 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.role" is not defined.' in /var/www/html/base/CComponent.php:120
Stack trace:
#0 /var/www/html/web/auth/CWebUser.php(97): CComponent->__get('role')
#1 /var/www/html/testapp/protected/views/layouts/main.php(40): CWebUser->__get('role')
#2 /var/www/html/web/CBaseController.php(119): require('/var/www/html/t...')
#3 /var/www/html/web/CBaseController.php(88): CBaseController->renderInternal('/var/www/html/t...', Array, true)
#4 /var/www/html/web/CController.php(642): CBaseController->renderFile('/var/www/html/t...', Array, true)
#5 /var/www/html/testapp/protected/controllers/SiteController.php(28): CController->render('index')
#6 /var/www/html/web/actions/CInlineAction.php(32): SiteController->actionIndex()
#7 /var/www/html/web/CController.php(300): CInlineAction->run()
#8 /var/www/html/web/CController.php(278): CController->runAction(Object(CInlineAction))
#9 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/html/web/CWebApplication.php(332): CController->run('')
#11 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('')
#12 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#13 /var/www/html/testapp/index.php(11): CApplication->run()
#14 {main} REQUEST_URI=/testapp/index.php
2021/08/04 11:49:17 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.role" is not defined.' in /var/www/html/base/CComponent.php:120
Stack trace:
#0 /var/www/html/web/auth/CWebUser.php(97): CComponent->__get('role')
#1 /var/www/html/testapp/protected/views/layouts/main.php(40): CWebUser->__get('role')
#2 /var/www/html/web/CBaseController.php(119): require('/var/www/html/t...')
#3 /var/www/html/web/CBaseController.php(88): CBaseController->renderInternal('/var/www/html/t...', Array, true)
#4 /var/www/html/web/CController.php(642): CBaseController->renderFile('/var/www/html/t...', Array, true)
#5 /var/www/html/testapp/protected/controllers/SiteController.php(28): CController->render('index')
#6 /var/www/html/web/actions/CInlineAction.php(32): SiteController->actionIndex()
#7 /var/www/html/web/CController.php(300): CInlineAction->run()
#8 /var/www/html/web/CController.php(278): CController->runAction(Object(CInlineAction))
#9 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/html/web/CWebApplication.php(332): CController->run('')
#11 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('')
#12 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#13 /var/www/html/testapp/index.php(11): CApplication->run()
#14 {main} REQUEST_URI=/testapp/index.php
2021/08/04 11:49:17 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.role" is not defined.' in /var/www/html/base/CComponent.php:120
Stack trace:
#0 /var/www/html/web/auth/CWebUser.php(97): CComponent->__get('role')
#1 /var/www/html/testapp/protected/views/layouts/main.php(40): CWebUser->__get('role')
#2 /var/www/html/web/CBaseController.php(119): require('/var/www/html/t...')
#3 /var/www/html/web/CBaseController.php(88): CBaseController->renderInternal('/var/www/html/t...', Array, true)
#4 /var/www/html/web/CController.php(642): CBaseController->renderFile('/var/www/html/t...', Array, true)
#5 /var/www/html/testapp/protected/controllers/SiteController.php(28): CController->render('index')
#6 /var/www/html/web/actions/CInlineAction.php(32): SiteController->actionIndex()
#7 /var/www/html/web/CController.php(300): CInlineAction->run()
#8 /var/www/html/web/CController.php(278): CController->runAction(Object(CInlineAction))
#9 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/html/web/CWebApplication.php(332): CController->run('')
#11 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('')
#12 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#13 /var/www/html/testapp/index.php(11): CApplication->run()
#14 {main} REQUEST_URI=/testapp/index.php
2021/08/04 11:49:18 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.role" is not defined.' in /var/www/html/base/CComponent.php:120
Stack trace:
#0 /var/www/html/web/auth/CWebUser.php(97): CComponent->__get('role')
#1 /var/www/html/testapp/protected/views/layouts/main.php(40): CWebUser->__get('role')
#2 /var/www/html/web/CBaseController.php(119): require('/var/www/html/t...')
#3 /var/www/html/web/CBaseController.php(88): CBaseController->renderInternal('/var/www/html/t...', Array, true)
#4 /var/www/html/web/CController.php(642): CBaseController->renderFile('/var/www/html/t...', Array, true)
#5 /var/www/html/testapp/protected/controllers/SiteController.php(66): CController->render('login', Array)
#6 /var/www/html/web/actions/CInlineAction.php(32): SiteController->actionLogin()
#7 /var/www/html/web/CController.php(300): CInlineAction->run()
#8 /var/www/html/web/CController.php(278): CController->runAction(Object(CInlineAction))
#9 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/html/web/CWebApplication.php(332): CController->run('login')
#11 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('site/login')
#12 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#13 /var/www/html/testapp/index.php(11): CApplication->run()
#14 {main} REQUEST_URI=/testapp/site/login
2021/08/04 11:49:18 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.role" is not defined.' in /var/www/html/base/CComponent.php:120
Stack trace:
#0 /var/www/html/web/auth/CWebUser.php(97): CComponent->__get('role')
#1 /var/www/html/testapp/protected/views/layouts/main.php(40): CWebUser->__get('role')
#2 /var/www/html/web/CBaseController.php(119): require('/var/www/html/t...')
#3 /var/www/html/web/CBaseController.php(88): CBaseController->renderInternal('/var/www/html/t...', Array, true)
#4 /var/www/html/web/CController.php(642): CBaseController->renderFile('/var/www/html/t...', Array, true)
#5 /var/www/html/testapp/protected/controllers/SiteController.php(28): CController->render('index')
#6 /var/www/html/web/actions/CInlineAction.php(32): SiteController->actionIndex()
#7 /var/www/html/web/CController.php(300): CInlineAction->run()
#8 /var/www/html/web/CController.php(278): CController->runAction(Object(CInlineAction))
#9 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/html/web/CWebApplication.php(332): CController->run('index')
#11 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('site/index')
#12 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#13 /var/www/html/testapp/index.php(11): CApplication->run()
#14 {main} REQUEST_URI=/testapp/site/index
2021/08/04 11:49:18 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.role" is not defined.' in /var/www/html/base/CComponent.php:120
Stack trace:
#0 /var/www/html/web/auth/CWebUser.php(97): CComponent->__get('role')
#1 /var/www/html/testapp/protected/views/layouts/main.php(40): CWebUser->__get('role')
#2 /var/www/html/web/CBaseController.php(119): require('/var/www/html/t...')
#3 /var/www/html/web/CBaseController.php(88): CBaseController->renderInternal('/var/www/html/t...', Array, true)
#4 /var/www/html/web/CController.php(642): CBaseController->renderFile('/var/www/html/t...', Array, true)
#5 /var/www/html/testapp/protected/controllers/SiteController.php(66): CController->render('login', Array)
#6 /var/www/html/web/actions/CInlineAction.php(32): SiteController->actionLogin()
#7 /var/www/html/web/CController.php(300): CInlineAction->run()
#8 /var/www/html/web/CController.php(278): CController->runAction(Object(CInlineAction))
#9 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/html/web/CWebApplication.php(332): CController->run('login')
#11 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('site/login')
#12 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#13 /var/www/html/testapp/index.php(11): CApplication->run()
#14 {main} REQUEST_URI=/testapp/site/login
2021/08/04 11:49:59 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.role" is not defined.' in /var/www/html/base/CComponent.php:120
Stack trace:
#0 /var/www/html/web/auth/CWebUser.php(97): CComponent->__get('role')
#1 /var/www/html/testapp/protected/views/layouts/main.php(40): CWebUser->__get('role')
#2 /var/www/html/web/CBaseController.php(119): require('/var/www/html/t...')
#3 /var/www/html/web/CBaseController.php(88): CBaseController->renderInternal('/var/www/html/t...', Array, true)
#4 /var/www/html/web/CController.php(642): CBaseController->renderFile('/var/www/html/t...', Array, true)
#5 /var/www/html/testapp/protected/controllers/SiteController.php(28): CController->render('index')
#6 /var/www/html/web/actions/CInlineAction.php(32): SiteController->actionIndex()
#7 /var/www/html/web/CController.php(300): CInlineAction->run()
#8 /var/www/html/web/CController.php(278): CController->runAction(Object(CInlineAction))
#9 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/html/web/CWebApplication.php(332): CController->run('')
#11 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('')
#12 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#13 /var/www/html/testapp/index.php(11): CApplication->run()
#14 {main} REQUEST_URI=/testapp/
2021/08/04 11:50:50 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.role" is not defined.' in /var/www/html/base/CComponent.php:120
Stack trace:
#0 /var/www/html/web/auth/CWebUser.php(97): CComponent->__get('role')
#1 /var/www/html/testapp/protected/views/layouts/main.php(40): CWebUser->__get('role')
#2 /var/www/html/web/CBaseController.php(119): require('/var/www/html/t...')
#3 /var/www/html/web/CBaseController.php(88): CBaseController->renderInternal('/var/www/html/t...', Array, true)
#4 /var/www/html/web/CController.php(642): CBaseController->renderFile('/var/www/html/t...', Array, true)
#5 /var/www/html/testapp/protected/controllers/SiteController.php(28): CController->render('index')
#6 /var/www/html/web/actions/CInlineAction.php(32): SiteController->actionIndex()
#7 /var/www/html/web/CController.php(300): CInlineAction->run()
#8 /var/www/html/web/CController.php(278): CController->runAction(Object(CInlineAction))
#9 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/html/web/CWebApplication.php(332): CController->run('')
#11 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('')
#12 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#13 /var/www/html/testapp/index.php(11): CApplication->run()
#14 {main} REQUEST_URI=/testapp/
2021/08/04 11:52:51 [error] [exception.CException] exception 'CException' with message 'Property "WebUser.role" is not defined.' in /var/www/html/base/CComponent.php:120
Stack trace:
#0 /var/www/html/web/auth/CWebUser.php(97): CComponent->__get('role')
#1 /var/www/html/testapp/protected/views/layouts/main.php(41): CWebUser->__get('role')
#2 /var/www/html/web/CBaseController.php(119): require('/var/www/html/t...')
#3 /var/www/html/web/CBaseController.php(88): CBaseController->renderInternal('/var/www/html/t...', Array, true)
#4 /var/www/html/web/CController.php(642): CBaseController->renderFile('/var/www/html/t...', Array, true)
#5 /var/www/html/testapp/protected/controllers/SiteController.php(28): CController->render('index')
#6 /var/www/html/web/actions/CInlineAction.php(32): SiteController->actionIndex()
#7 /var/www/html/web/CController.php(300): CInlineAction->run()
#8 /var/www/html/web/CController.php(278): CController->runAction(Object(CInlineAction))
#9 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/html/web/CWebApplication.php(332): CController->run('')
#11 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('')
#12 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#13 /var/www/html/testapp/index.php(11): CApplication->run()
#14 {main} REQUEST_URI=/testapp/
